apiVersion: v2
kind: Service
metadata:
  name: poc2018
  labels:
    app: apache2
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    nodePort: 31295
    protocol: TCP
  selector:
    app: apache2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: poc2018
  labels:
    app: apache2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache2
  template:
    metadata:
      labels:
        app: apache2
    spec:
      containers:
      - name: apache2
        image: manishit244/new
        ports:
        - containerPort: 80
